### PR TITLE
fix #343

### LINKED ISSUE #343: ERROR task_darwinia_ethereum::service::redeem] ethereum redeem err KVError received from microkv with message: invalid type: string "13750646", expected usize
```
[2021-12-06T08:13:57Z ERROR task_darwinia_ethereum::service::redeem] ethereum redeem err KVError received from microkv with message: invalid type: string "13750646", expected usize

    Stack backtrace:
       0: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
       1: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
       2: <lifeline::spawn::LifelineFuture<F> as core::future::future::Future>::poll
       3: tokio::runtime::task::harness::Harness<T,S>::poll
       4: std::thread::local::LocalKey<T>::with
       5: tokio::runtime::thread_pool::worker::Context::run_task
       6: tokio::runtime::thread_pool::worker::Context::run
       7: tokio::macros::scoped_tls::ScopedKey<T>::set
       8: tokio::runtime::thread_pool::worker::run
       9: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
      10: tokio::runtime::task::harness::Harness<T,S>::poll
      11: tokio::runtime::blocking::pool::Inner::run
      12: std::sys_common::backtrace::__rust_begin_short_backtrace
      13: core::ops::function::FnOnce::call_once{{vtable.shim}}
      14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                 at /rustc/48a5999fceeea84a8971634355287faa349909d4/library/alloc/src/boxed.rs:1694:9
      15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                 at /rustc/48a5999fceeea84a8971634355287faa349909d4/library/alloc/src/boxed.rs:1694:9
      16: std::sys::unix::thread::Thread::new::thread_start
                 at /rustc/48a5999fceeea84a8971634355287faa349909d4/library/std/src/sys/unix/thread.rs:108:17
      17: start_thread
      18: clone
```

### PR DESCRIPTION
**Pull request by fewensa**
fix #343

### CODE REVIEW

File: task/task-darwinia-ethereum/src/migrate/v0.rs [hunk 1]
```diff
@@ -16,7 +16,7 @@ fn migrate_scan_darwinia(microkv: &NamespaceMicroKV) -> anyhow::Result<()> {
     let key = "last-tracked-darwinia-block";
     let block_darwinia: Option<u64> = microkv.get_as(key)?;
     if let Some(block) = block_darwinia {
-        microkv.put("scan.darwinia.next", &format!("{}", block))?;
+        microkv.put("scan.darwinia.next", &block)?;
```
Comment (fewensa) [inline task/task-darwinia-ethereum/src/migrate/v0.rs:19]: I think currently no one upgrade to the latest version. so changing old migrate is safe.

**Review by HackFisher — APPROVED** [review]
