### PR TITLE
Fix try_lock fail possibilities

### LINKED ISSUE #65: ERROR darwinia_bridger::service::redeem] try_lock failed
Could cause redeem service stop running?

### PR DESCRIPTION
**Pull request by HackFisher**
Closes #65

### CODE REVIEW

**Review by wuminzhe — APPROVED** [review]

File: src/service/ethereum.rs [hunk 1]
```diff
@@ -149,26 +149,36 @@ impl<T: Transport + std::marker::Sync> Service for EthereumService<T> {
...
+                    trace!("\t{:?}", &tx.tx_hash);
                 }
+            }
 
+            if let Ok(mut cache_cloned) = cache.try_lock() {
                 cache_cloned.txpool.append(&mut txs);
                 cache_cloned.start = block_number;
                 drop(cache_cloned);
+            } else {
+                error!("try_lock failed");
```
Comment (clearloop) [inline src/service/ethereum.rs:181]: This should be `debug` log which contains it emits in witch service

File: src/service/relay.rs [hunk 2]
```diff
@@ -47,15 +47,18 @@ impl Service for RelayService {
...
                     let max = max.block.to_owned();
                     if let Err(err) = self.affirm(max + 1).await {
-                        error!("{:?}", err);
+                        trace!("{:?}", err);
                     };
                 }
 
                 drop(cache_cloned);
+            } else {
+                error!("try_lock failed");
```
Comment (clearloop) [inline src/service/relay.rs:61]: `debug!("try_lock cache failed in RELAY service");`
