### PR TITLE
Fix roles checking

### LINKED ISSUE #148: Role checking should consider block height

### PR DESCRIPTION
**Pull request by wuminzhe**
fix #148

### CODE REVIEW

File: src/api/darwinia.rs [hunk 1]
```diff
@@ -316,37 +316,37 @@ impl Darwinia {
...
 		message: EcdsaMessage,
 	) -> Result<H256> {
-		if self.sender.is_authority().await? {
-			let signature = self.sender.ecdsa_sign(&message)?;
-			match &self.sender.real {
-				// proxy
-				Some(real) => {
-					trace!("Proxyed ecdsa sign and submit authorities to darwinia");
-					let submit_signed_authorities = SubmitSignedAuthorities { signature };
+		// TODO: check
```
Comment (wuminzhe) [inline src/api/darwinia.rs:319]: checking latest authorities to sign will be put here in next PR

**Comment by HackFisher** [comment]
@wuminzhe There are conflicts need to resolve

**Review by HackFisher — APPROVED** [review]
